# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_adapter_postgres"
version = "0.1.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Postgres filesystem support for `clinvoice_adapter` 0.8"

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice_adapter_postgres"

[dependencies]
clinvoice_adapter = {branch="release/0.11", git = "https://github.com/Iron-E/clinvoice_adapter"}
clinvoice_error = {branch = "release/0.3", git = "https://github.com/Iron-E/clinvoice_error"}
clinvoice_finance = {branch = "release/0.3", git = "https://github.com/Iron-E/clinvoice_finance"}
clinvoice_match = {branch = "release/0.4", git = "https://github.com/Iron-E/clinvoice_match"}
clinvoice_schema = {branch = "release/0.8", git = "https://github.com/Iron-E/clinvoice_schema"}

async-trait = "0.1"
futures = "0.3"
humantime = "2"
shellexpand = "2"
sqlx = {features = ["chrono", "decimal", "macros", "postgres", "runtime-tokio-rustls", "tls"], version = "0.5"}
thiserror = "1"

[dev-dependencies]
dotenv = "0.15.0"
lazy_static = "1"
pretty_assertions = "1"
tokio = {features = ["macros", "rt-multi-thread"], version = "1"}

[features]
default = []
